### ISSUE TITLE
Expiration jwt whitout logout vue.js

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#11]
Quand le token JWT expire, vue.js ne logout pas, donc l'utilisateur reste identifier sur le front mais n'a pas accès aux contenus du backoffice.

**Comment by Poloriba** [comment]
- Create autologout Component in Component/autologout.vue (Actually in commentary)
- Make an Auth Guard in Router/index.js, Authguard check the status of Token before redirection (Actually in commentary to).

To fix this issue,we need to fix before the Jwt management, because Authstatus is not update when token expirate.
